/**
 * Planilhas de treinamento multisport — ciclismo, natação, brick, triathlon.
 * Templates de referência — adaptação por treinador recomendada.
 *
 * Abreviações:
 *   RO=Rodagem | END=Endurance | SS=Sweet Spot | LIM=Limiar | INT=Intervalado
 *   NAT=Natação | CSS=Ritmo crítico natação | TEC=Técnica natação
 *   BRICK=Brick treino combinado | TRI=Treino triathlon
 *   D=Descanso | MOB=Mobilidade | ATIV=Aquecimento/ativação
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export type MultisportGoal =
  | "SPRINT_TRIATHLON"
  | "OLIMPICO"
  | "GRAN_FONDO"
  | "BIKE_BASE"
  | "SWIM_TECHNIQUE"
  | "BRICK_BLOCK";

export type MultisportLevel = "iniciante" | "intermediario" | "avancado";

export interface MultisportDayWorkout {
  day: string;
  sport: "RUN" | "BIKE" | "SWIM" | "STRENGTH" | "MOBILITY" | "BRICK" | "REST";
  workout: string;
  durationMin?: number;
  notes?: string;
}

export interface MultisportWeek {
  week: number;
  phase: string;
  days: MultisportDayWorkout[];
}

export interface MultisportTemplate {
  id: string;
  goal: MultisportGoal;
  level: MultisportLevel;
  durationWeeks: 4 | 6 | 8 | 12;
  title: string;
  description: string;
  targetDistribution?: { runPct: number; bikePct: number; swimPct: number; strengthPct: number };
  weeks: MultisportWeek[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

type DaySpec = [MultisportDayWorkout["sport"], string, number?];

function mw(
  n: number,
  phase: string,
  seg: DaySpec,
  ter: DaySpec,
  qua: DaySpec,
  qui: DaySpec,
  sex: DaySpec,
  sab: DaySpec,
  dom: DaySpec,
): MultisportWeek {
  const DAYS = ["SEG", "TER", "QUA", "QUI", "SEX", "SAB", "DOM"];
  return {
    week: n,
    phase,
    days: [seg, ter, qua, qui, sex, sab, dom].map(([sport, workout, durationMin], i) => ({
      day: DAYS[i],
      sport,
      workout,
      ...(durationMin ? { durationMin } : {}),
    })),
  };
}

const D: DaySpec = ["REST",     "DESCANSO",   0];
const MOB: DaySpec = ["MOBILITY","MOB 20min", 20];

// ── Sprint Triathlon — 8 semanas (Iniciante) ──────────────────────────────────

const sprintTriathlonIni8w: MultisportTemplate = {
  id: "sprint-tri-ini-8w",
  goal: "SPRINT_TRIATHLON",
  level: "iniciante",
  durationWeeks: 8,
  title: "Sprint Triathlon — Iniciante (8 semanas)",
  description: "Prepare-se para completar seu primeiro Sprint Triathlon (750m nado, 20km bike, 5km corrida).",
  targetDistribution: { runPct: 30, bikePct: 40, swimPct: 25, strengthPct: 5 },
  weeks: [
    mw(1, "Base",
      ["SWIM",     "TEC 1000m — técnica básica + respiração bilateral",   40],
      ["BIKE",     "END 45min Z2 — bicicleta plana, RPE 4-5",             45],
      ["RUN",      "RO 20min Z2 — leve",                                  20],
      ["SWIM",     "END 1200m — 6×200m descanso 30s",                     40],
      D,
      ["BRICK",    "BIKE 30min Z2 + RUN 10min Z2 — transição rápida",     45],
      MOB,
    ),
    mw(2, "Base",
      ["SWIM",     "TEC 1200m — drills de entrada de mão + crol",         45],
      ["BIKE",     "END 50min Z2",                                         50],
      ["RUN",      "RO 25min Z2",                                          25],
      ["SWIM",     "END 1400m — 7×200m desc 25s",                         45],
      D,
      ["BRICK",    "BIKE 40min Z2 + RUN 15min Z2",                        60],
      MOB,
    ),
    mw(3, "Construção",
      ["SWIM",     "INT 1500m — 6×100m @ CSS+5s desc 20s + aquecimento",  50],
      ["BIKE",     "SS 50min — 20min @ 85% FTP no meio",                   55],
      ["RUN",      "INT 6×400m pace 5km pausa 90s",                        35],
      ["SWIM",     "END 1600m — 8×200m desc 20s",                          50],
      D,
      ["BRICK",    "BIKE 50min (SS 20min) + RUN 20min Z2",                 75],
      MOB,
    ),
    mw(4, "Recuperação",
      ["SWIM",     "TEC 1000m — foco na rolagem de quadril",               35],
      ["BIKE",     "END 40min Z1-Z2 — recuperação ativa",                  40],
      ["RUN",      "RO 20min Z1",                                           20],
      D,
      ["SWIM",     "END 1000m leve",                                        35],
      D,
      MOB,
    ),
    mw(5, "Específico",
      ["SWIM",     "INT 1800m — 9×200m @ CSS+3s desc 20s",                 55],
      ["BIKE",     "SS 60min — 2×15min @ 88% FTP rec 5min",                65],
      ["RUN",      "TEMPO 30min — 20min @ limiar",                          35],
      ["SWIM",     "END 1600m + 4×50m sprint desc 45s",                    50],
      D,
      ["BRICK",    "BIKE 60min (2×15min SS) + RUN 25min Z2-Z3",            90],
      MOB,
    ),
    mw(6, "Específico",
      ["SWIM",     "INT 2000m — 10×200m @ CSS desc 15s",                   60],
      ["BIKE",     "LIM 55min — 2×12min @ 100% FTP rec 5min",              60],
      ["RUN",      "INT 8×400m pace 5km pausa 75s",                         45],
      ["SWIM",     "SIMULADO 750m contínuo @ pace alvo",                    30],
      D,
      ["BRICK",    "BIKE 70min Z2-Z3 + RUN 30min Z2",                      105],
      MOB,
    ),
    mw(7, "Pico",
      ["SWIM",     "INT 1600m — foco ritmo de prova",                       50],
      ["BIKE",     "SS 50min — 1×25min @ 87% FTP",                         55],
      ["RUN",      "PROGRESSIVO 30min — últimos 10min Z3",                  30],
      ["SWIM",     "END 1200m leve",                                         40],
      D,
      ["BRICK",    "SIMULADO: NAT 750m + BIKE 20km + RUN 5km",             120],
      MOB,
    ),
    mw(8, "Taper",
      ["SWIM",     "TEC 1000m leve + 4×50m ritmo prova",                    35],
      ["BIKE",     "END 40min — ativação + 5min @ ritmo prova",             45],
      ["RUN",      "RO 20min Z1 + 4×30s strideouts",                        25],
      D,
      D,
      ["REST",     "DESCANSO — preparação mental e material",                 0],
      ["REST",     "PROVA — Sprint Triathlon",                                0],
    ),
  ],
};

// ── Olympic Triathlon — 12 semanas (Intermediário) ────────────────────────────

const olimpicoInter12w: MultisportTemplate = {
  id: "olimpico-inter-12w",
  goal: "OLIMPICO",
  level: "intermediario",
  durationWeeks: 12,
  title: "Triathlon Olímpico — Intermediário (12 semanas)",
  description: "Periodização para completar um Olímpico (1,5km nado + 40km bike + 10km corrida) em tempo competitivo.",
  targetDistribution: { runPct: 25, bikePct: 45, swimPct: 25, strengthPct: 5 },
  weeks: [
    mw(1, "Base",
      ["SWIM",     "TEC 2000m — drills + nado contínuo",                    60],
      ["BIKE",     "END 75min Z2",                                           75],
      ["RUN",      "RO 35min Z2",                                            35],
      ["SWIM",     "INT 2200m — 11×200m @ CSS+5s desc 20s",                 65],
      D,
      ["BIKE",     "END 90min Z2 — longa base",                              90],
      MOB,
    ),
    mw(2, "Base",
      ["SWIM",     "INT 2400m — 12×200m @ CSS+3s desc 20s",                 70],
      ["BIKE",     "SS 75min — 2×20min @ 87% FTP",                          80],
      ["RUN",      "INT 8×600m pausa 90s",                                   50],
      ["SWIM",     "END 2000m + 6×50m sprint",                              60],
      D,
      ["BRICK",    "BIKE 90min (SS 30min) + RUN 25min Z2",                  120],
      MOB,
    ),
    mw(3, "Base",
      ["SWIM",     "INT 2600m — 8×300m @ CSS+3s desc 25s",                  75],
      ["BIKE",     "LIM 80min — 2×15min @ 100% FTP rec 5min",               85],
      ["RUN",      "TEMPO 40min — 25min @ limiar",                           45],
      ["SWIM",     "END 2200m",                                               65],
      D,
      ["BRICK",    "BIKE 100min Z2-Z3 + RUN 30min Z2",                      135],
      MOB,
    ),
    mw(4, "Recuperação",
      ["SWIM",     "TEC 1500m leve",                                         45],
      ["BIKE",     "END 60min Z1-Z2",                                        60],
      ["RUN",      "RO 30min Z1",                                            30],
      D,
      ["SWIM",     "END 1500m leve",                                         45],
      D,
      MOB,
    ),
    mw(5, "Construção",
      ["SWIM",     "INT 2800m — 8×300m @ CSS+2s desc 20s",                  80],
      ["BIKE",     "SS 90min — 3×20min @ 88% FTP rec 5min",                 95],
      ["RUN",      "INT 10×600m pausa 75s",                                  60],
      ["SWIM",     "END 2400m + 8×50m sprint",                               70],
      D,
      ["BRICK",    "BIKE 110min (SS 40min) + RUN 35min Z2-Z3",              150],
      MOB,
    ),
    mw(6, "Construção",
      ["SWIM",     "INT 3000m — 6×500m @ CSS+3s desc 30s",                  85],
      ["BIKE",     "LIM 85min — 3×12min @ 102% FTP rec 4min",               90],
      ["RUN",      "TEMPO 45min — 30min @ limiar",                           50],
      ["SWIM",     "SIMULADO 1500m contínuo @ pace alvo",                    45],
      D,
      ["BRICK",    "BIKE 120min Z2-Z3 + RUN 40min Z2",                      165],
      MOB,
    ),
    mw(7, "Construção",
      ["SWIM",     "INT 3000m — 10×300m @ CSS desc 20s",                    85],
      ["BIKE",     "SS 90min — 2×30min @ 87% FTP",                          95],
      ["RUN",      "INT 6×1000m pausa 2min",                                 65],
      ["SWIM",     "END 2600m",                                               75],
      D,
      ["BRICK",    "BIKE 130min + RUN 40min Z2",                            175],
      MOB,
    ),
    mw(8, "Recuperação",
      ["SWIM",     "TEC 1800m leve",                                         55],
      ["BIKE",     "END 70min Z1-Z2",                                        70],
      ["RUN",      "RO 35min Z1",                                             35],
      D,
      ["SWIM",     "END 1600m leve",                                         48],
      D,
      MOB,
    ),
    mw(9, "Específico",
      ["SWIM",     "INT 3200m — 8×400m @ CSS+1s desc 20s",                  90],
      ["BIKE",     "LIM 90min — 3×15min @ 102% FTP rec 4min",               95],
      ["RUN",      "TEMPO 50min — 35min @ limiar",                           55],
      ["SWIM",     "SIMULADO 1500m + 4×100m sprint",                         55],
      D,
      ["BRICK",    "BIKE 140min (LIM 25min) + RUN 45min Z2-Z3",             190],
      MOB,
    ),
    mw(10, "Específico",
      ["SWIM",     "INT 3000m — foco ritmo de prova",                        85],
      ["BIKE",     "SS 90min — ritmo prova 40km",                            95],
      ["RUN",      "PROGRESSIVO 50min — últimos 15min Z3",                   55],
      ["SWIM",     "END 2400m",                                               70],
      D,
      ["BRICK",    "SIMULADO: NAT 1500m + BIKE 40km + RUN 10km",            180],
      MOB,
    ),
    mw(11, "Taper",
      ["SWIM",     "INT 2400m — ritmo prova + sprint final",                 70],
      ["BIKE",     "SS 70min — 1×25min @ ritmo prova",                       75],
      ["RUN",      "INT 6×800m pausa 2min",                                   55],
      ["SWIM",     "END 1800m leve",                                          55],
      D,
      ["BRICK",    "BIKE 60min Z2 + RUN 25min Z2 — ativação",                90],
      MOB,
    ),
    mw(12, "Taper / Prova",
      ["SWIM",     "TEC 1200m leve — ativação",                              40],
      ["BIKE",     "END 50min — 8min @ ritmo prova",                         50],
      ["RUN",      "RO 25min + 4×30s strideouts",                            30],
      D,
      D,
      ["REST",     "DESCANSO — preparação final",                              0],
      ["REST",     "PROVA — Triathlon Olímpico",                               0],
    ),
  ],
};

// ── Gran Fondo / Base Ciclismo — 8 semanas ────────────────────────────────────

const granFondoBike8w: MultisportTemplate = {
  id: "gran-fondo-bike-8w",
  goal: "GRAN_FONDO",
  level: "intermediario",
  durationWeeks: 8,
  title: "Gran Fondo / Base Ciclismo (8 semanas)",
  description: "Construa base aeróbica para um gran fondo de 80–130km com foco em endurance e sweet spot.",
  targetDistribution: { runPct: 5, bikePct: 85, swimPct: 0, strengthPct: 10 },
  weeks: [
    mw(1, "Base",
      D,
      ["BIKE",     "END 60min Z2 — cadência 85-90 rpm",                     60],
      ["STRENGTH", "FORCA 40min — pernas, isquiotibiais, glúteos",           40],
      ["BIKE",     "SS 60min — 15min @ 85% FTP no meio",                     65],
      D,
      ["BIKE",     "END 90min Z2 — longa base",                              90],
      MOB,
    ),
    mw(2, "Base",
      D,
      ["BIKE",     "SS 65min — 20min @ 85% FTP",                            65],
      ["STRENGTH", "FORCA 45min — ênfase monopodalismo",                     45],
      ["BIKE",     "LIM 60min — 2×8min @ 100% FTP rec 5min",                65],
      D,
      ["BIKE",     "END 110min Z2 — manter cadência",                       110],
      MOB,
    ),
    mw(3, "Construção",
      D,
      ["BIKE",     "SS 75min — 2×15min @ 87% FTP rec 5min",                 80],
      ["STRENGTH", "FORCA 45min",                                             45],
      ["BIKE",     "LIM 70min — 2×12min @ 100% FTP rec 5min",               75],
      D,
      ["BIKE",     "END 130min Z2 — terreno variado",                       130],
      MOB,
    ),
    mw(4, "Recuperação",
      D,
      ["BIKE",     "END 50min Z1-Z2 — pernas livres",                       50],
      D,
      ["BIKE",     "END 55min Z1-Z2",                                        55],
      D,
      ["BIKE",     "END 80min Z2",                                           80],
      MOB,
    ),
    mw(5, "Específico",
      D,
      ["BIKE",     "SS 80min — 2×20min @ 88% FTP",                          85],
      ["STRENGTH", "FORCA 45min — manutenção",                               45],
      ["BIKE",     "LIM 75min — 3×10min @ 100% FTP rec 4min",               80],
      D,
      ["BIKE",     "END 150min Z2 — simular percurso",                      150],
      MOB,
    ),
    mw(6, "Específico",
      D,
      ["BIKE",     "SS 85min — 3×15min @ 88% FTP",                          90],
      ["STRENGTH", "FORCA 40min",                                             40],
      ["BIKE",     "LIM 80min — 2×15min @ 100% FTP rec 5min",               85],
      D,
      ["BIKE",     "END 170min Z2-Z3 — terreno subida",                     170],
      MOB,
    ),
    mw(7, "Taper",
      D,
      ["BIKE",     "SS 65min — 1×20min @ 87% FTP",                          70],
      D,
      ["BIKE",     "LIM 55min — 2×8min @ 100% FTP rec 5min",                60],
      D,
      ["BIKE",     "END 100min Z2 — ativação semana longa",                 100],
      MOB,
    ),
    mw(8, "Taper / Prova",
      D,
      ["BIKE",     "END 50min — 3×5min @ ritmo prova rec 3min",             55],
      D,
      D,
      ["BIKE",     "END 35min Z1 — pernas soltas + strideouts",             35],
      ["REST",     "DESCANSO — preparação",                                    0],
      ["REST",     "PROVA — Gran Fondo",                                       0],
    ),
  ],
};

// ── Bloco de Natação Técnica — 6 semanas ─────────────────────────────────────

const swimTechnique6w: MultisportTemplate = {
  id: "swim-technique-6w",
  goal: "SWIM_TECHNIQUE",
  level: "iniciante",
  durationWeeks: 6,
  title: "Bloco de Técnica de Natação (6 semanas)",
  description: "Melhore sua técnica e eficiência na natação com foco em drills, SWOLF e CSS.",
  targetDistribution: { runPct: 0, bikePct: 0, swimPct: 95, strengthPct: 5 },
  weeks: [
    mw(1, "Técnica",
      ["SWIM",     "TEC 1000m — kicking, foco rotação quadril, catch-up drill",  35],
      D,
      ["SWIM",     "TEC 1200m — entrada da mão, 6×50m com palmar",               40],
      D,
      ["SWIM",     "TEC 1000m — respiração bilateral 3-5-3, nado contínuo",       35],
      D,
      MOB,
    ),
    mw(2, "Técnica + Volume",
      ["SWIM",     "TEC 1200m — drill pullbuoy + nado livre",                     40],
      D,
      ["SWIM",     "END 1500m — 6×200m foco SWOLF, descanso 30s",                50],
      D,
      ["SWIM",     "TEC 1200m — finger drag, high elbow drill",                   40],
      D,
      MOB,
    ),
    mw(3, "CSS Discovery",
      ["SWIM",     "TEC 1400m + TESTE CSS: 400m + 200m com 10min descanso",       60],
      D,
      ["SWIM",     "INT 1800m — 6×200m @ CSS+8s desc 30s",                        55],
      D,
      ["SWIM",     "TEC 1200m — drills + 200m @ CSS",                             45],
      D,
      MOB,
    ),
    mw(4, "Ritmo CSS",
      ["SWIM",     "INT 2000m — 8×200m @ CSS+5s desc 25s",                        60],
      D,
      ["SWIM",     "END 1600m contínuo — pace sustentável",                        50],
      D,
      ["SWIM",     "INT 1800m — 12×100m @ CSS+3s desc 20s",                        55],
      D,
      MOB,
    ),
    mw(5, "Volume + Eficiência",
      ["SWIM",     "INT 2200m — 8×250m @ CSS+3s desc 20s",                        65],
      D,
      ["SWIM",     "END 2000m contínuo — monitorar SWOLF",                         60],
      D,
      ["SWIM",     "INT 2000m — 10×200m @ CSS+2s desc 20s",                        60],
      D,
      MOB,
    ),
    mw(6, "Consolidação",
      ["SWIM",     "INT 2400m — 6×400m @ CSS+3s desc 30s",                        70],
      D,
      ["SWIM",     "TESTE: 400m + 200m para novo CSS",                             45],
      D,
      ["SWIM",     "END 2000m — pace alvo com foco técnico",                        60],
      D,
      MOB,
    ),
  ],
};

// ── Bloco Brick — 4 semanas ───────────────────────────────────────────────────

const brickBlock4w: MultisportTemplate = {
  id: "brick-block-4w",
  goal: "BRICK_BLOCK",
  level: "intermediario",
  durationWeeks: 4,
  title: "Bloco de Treinos Brick (4 semanas)",
  description: "Desenvolva a habilidade de transição bike→corrida com bricks progressivos semanais.",
  targetDistribution: { runPct: 30, bikePct: 55, swimPct: 0, strengthPct: 15 },
  weeks: [
    mw(1, "Base Brick",
      ["BIKE",     "END 50min Z2",                                           50],
      ["RUN",      "RO 25min Z2",                                            25],
      ["STRENGTH", "FORCA 35min — membros inferiores",                       35],
      ["SWIM",     "END 1500m (opcional — complementar)",                    45],
      D,
      ["BRICK",    "BIKE 45min Z2 → RUN 15min Z2 — transição <90s",         65],
      MOB,
    ),
    mw(2, "Progressão",
      ["BIKE",     "SS 55min — 15min @ 85% FTP",                            60],
      ["RUN",      "INT 6×400m pausa 90s",                                   40],
      ["STRENGTH", "FORCA 40min",                                             40],
      D,
      ["BIKE",     "END 60min Z2",                                           60],
      ["BRICK",    "BIKE 60min (SS 20min) → RUN 20min Z2-Z3",               85],
      MOB,
    ),
    mw(3, "Especificidade",
      ["BIKE",     "LIM 60min — 2×10min @ 100% FTP",                        65],
      ["RUN",      "TEMPO 35min — 20min @ limiar",                           40],
      ["STRENGTH", "FORCA 35min",                                             35],
      D,
      ["BIKE",     "END 55min Z2",                                           55],
      ["BRICK",    "BIKE 70min (LIM 20min) → RUN 25min Z2-Z3",              100],
      MOB,
    ),
    mw(4, "Consolidação",
      ["BIKE",     "SS 50min",                                               55],
      ["RUN",      "RO 30min Z2",                                            30],
      D,
      ["BRICK",    "BRICK SIMULADO — ritmo de prova bike+run",               90],
      D,
      D,
      MOB,
    ),
  ],
};

// ── Base Ciclismo — 8 semanas ─────────────────────────────────────────────────

const bikeBase8w: MultisportTemplate = {
  id: "bike-base-8w",
  goal: "BIKE_BASE",
  level: "iniciante",
  durationWeeks: 8,
  title: "Base de Ciclismo (8 semanas)",
  description: "Construa sua base aeróbica no ciclismo com progressão gradual de volume e introdução ao sweet spot.",
  targetDistribution: { runPct: 0, bikePct: 90, swimPct: 0, strengthPct: 10 },
  weeks: [
    mw(1, "Adaptação",
      D,
      ["BIKE",     "END 45min Z2 — cadência livre 80-95 rpm",               45],
      D,
      ["BIKE",     "END 50min Z2",                                           50],
      D,
      ["BIKE",     "END 70min Z2 — primeiro longão",                        70],
      MOB,
    ),
    mw(2, "Adaptação",
      D,
      ["BIKE",     "END 50min Z2 + 2×5min @ 78% FTP",                      55],
      ["STRENGTH", "FORCA 35min — agachamento e lunges",                    35],
      ["BIKE",     "END 55min Z2",                                           55],
      D,
      ["BIKE",     "END 80min Z2",                                           80],
      MOB,
    ),
    mw(3, "Base",
      D,
      ["BIKE",     "SS 55min — 15min @ 84% FTP",                            60],
      ["STRENGTH", "FORCA 40min",                                             40],
      ["BIKE",     "END 55min Z2",                                           55],
      D,
      ["BIKE",     "END 95min Z2",                                           95],
      MOB,
    ),
    mw(4, "Recuperação",
      D,
      ["BIKE",     "END 45min Z1-Z2 — leve",                                45],
      D,
      ["BIKE",     "END 45min Z1-Z2",                                        45],
      D,
      ["BIKE",     "END 65min Z2",                                           65],
      MOB,
    ),
    mw(5, "Desenvolvimento",
      D,
      ["BIKE",     "SS 65min — 2×15min @ 86% FTP rec 4min",                 70],
      ["STRENGTH", "FORCA 40min",                                             40],
      ["BIKE",     "LIM 60min — 2×8min @ 98% FTP rec 5min",                 65],
      D,
      ["BIKE",     "END 110min Z2",                                          110],
      MOB,
    ),
    mw(6, "Desenvolvimento",
      D,
      ["BIKE",     "SS 70min — 2×18min @ 87% FTP rec 4min",                 75],
      ["STRENGTH", "FORCA 40min",                                             40],
      ["BIKE",     "LIM 65min — 2×10min @ 100% FTP rec 5min",               70],
      D,
      ["BIKE",     "END 120min Z2 — terreno variado",                       120],
      MOB,
    ),
    mw(7, "Pico de carga",
      D,
      ["BIKE",     "SS 75min — 3×15min @ 87% FTP rec 4min",                 80],
      ["STRENGTH", "FORCA 35min — manutenção",                               35],
      ["BIKE",     "LIM 70min — 3×10min @ 100% FTP rec 4min",               75],
      D,
      ["BIKE",     "END 135min Z2 + 15min Z3",                              150],
      MOB,
    ),
    mw(8, "Consolidação",
      D,
      ["BIKE",     "SS 60min — 1×25min @ 87% FTP",                          65],
      D,
      ["BIKE",     "LIM 55min — 2×8min @ 100% FTP rec 5min",                60],
      D,
      ["BIKE",     "END 100min Z2 — foco em eficiência",                    100],
      MOB,
    ),
  ],
};

// ── Exportações ───────────────────────────────────────────────────────────────

export const multisportTemplates: MultisportTemplate[] = [
  sprintTriathlonIni8w,
  olimpicoInter12w,
  granFondoBike8w,
  bikeBase8w,
  swimTechnique6w,
  brickBlock4w,
];

export function getMultisportTemplate(goal: MultisportGoal, level: MultisportLevel): MultisportTemplate | undefined {
  return multisportTemplates.find((t) => t.goal === goal && t.level === level)
    ?? multisportTemplates.find((t) => t.goal === goal);
}

export const MULTISPORT_GOALS: Record<MultisportGoal, { label: string; emoji: string; description: string }> = {
  SPRINT_TRIATHLON: { label: "Sprint Triathlon",     emoji: "🏅", description: "750m + 20km + 5km" },
  OLIMPICO:         { label: "Triathlon Olímpico",   emoji: "🏅", description: "1,5km + 40km + 10km" },
  GRAN_FONDO:       { label: "Gran Fondo",            emoji: "🚴", description: "80–130km ciclismo" },
  BIKE_BASE:        { label: "Base Ciclismo",         emoji: "🚴", description: "8 semanas de base" },
  SWIM_TECHNIQUE:   { label: "Técnica de Natação",   emoji: "🏊", description: "6 semanas CSS + drills" },
  BRICK_BLOCK:      { label: "Bloco Brick",           emoji: "⚡", description: "4 semanas bike→run" },
};
